import { useState } from 'react';
import { useTheme } from '../contexts/ThemeContext';
import { OutputHeader } from './OutputHeader';
import { SummaryBar } from './SummaryBar';
import { ExportRow } from './ExportRow';
import { SystemCard } from './SystemCard';
import { SummaryTable } from './SummaryTable';
import type { SessionResult } from '../types/chat';

interface OutputPanelProps {
  result: SessionResult;
  onBack: () => void;
}

export function OutputPanel({ result, onBack }: OutputPanelProps) {
  const { theme } = useTheme();
  const [clientName, setClientName] = useState(result.clientName);
  const resultWithName: SessionResult = { ...result, clientName };
  const isDark = theme === 'dark';

  return (
    <div className="flex-1 overflow-y-auto px-4 sm:px-5 py-5">
      <OutputHeader
        clientName={clientName}
        onClientNameChange={setClientName}
        systemCount={result.systems.length}
        sessionType={result.sessionType}
        onBack={onBack}
      />

      <SummaryBar systems={result.systems} />

      <ExportRow result={resultWithName} />

      <div className="mt-5 space-y-3">
        <h3 className={`text-xs font-semibold uppercase tracking-[0.16em] ${isDark ? 'text-white/45' : 'text-black/45'}`}>Systems</h3>
        {result.systems.map((system, i) => (
          <SystemCard key={i} system={system} index={i} />
        ))}
      </div>

      {result.sessionType === 'platform' && result.systems.length > 1 && (
        <SummaryTable systems={result.systems} />
      )}

      <div className={`mt-8 text-center text-xs pb-4 ${isDark ? 'text-white/25' : 'text-black/35'}`}>
        Generated by Autonome AI ROI Calculator - {new Date().toLocaleDateString()}
      </div>
    </div>
  );
}
