import { useState } from 'react';
import { OutputHeader } from './OutputHeader';
import { SummaryBar } from './SummaryBar';
import { ExportRow } from './ExportRow';
import { SystemCard } from './SystemCard';
import { SummaryTable } from './SummaryTable';
import type { SessionResult } from '../types/chat';

interface OutputPanelProps {
  result: SessionResult;
  onBack: () => void;
}

export function OutputPanel({ result, onBack }: OutputPanelProps) {
  const [clientName, setClientName] = useState(result.clientName);
  const resultWithName: SessionResult = { ...result, clientName };

  return (
    <div className="flex-1 overflow-y-auto py-4">
      <OutputHeader
        clientName={clientName}
        onClientNameChange={setClientName}
        systemCount={result.systems.length}
        sessionType={result.sessionType}
        onBack={onBack}
      />

      <SummaryBar systems={result.systems} />

      <ExportRow result={resultWithName} />

      <div className="mt-4 space-y-3">
        <h3 className="text-white/50 text-xs font-semibold uppercase tracking-wider">Systems</h3>
        {result.systems.map((system, i) => (
          <SystemCard key={i} system={system} index={i} />
        ))}
      </div>

      {result.sessionType === 'platform' && result.systems.length > 1 && (
        <SummaryTable systems={result.systems} />
      )}

      <div className="mt-8 text-center text-white/20 text-xs pb-4">
        Generated by Autonome AI ROI Calculator · {new Date().toLocaleDateString()}
      </div>
    </div>
  );
}
